name: CI pipeline
#Trigger pipeline on push to main or pull requests
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

env:
  BRANCH: ${{ github.head_ref || github.ref_name}}
  PYTHON_VERSION: '3.10'
concurrency:
  group: ${{ github.head_ref || github.ref_name}}
  cancel-in-progress: true
  
jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      #CHECK OUT THE CODE
        #This means githubActions => will copy the code from github[repo] and clone it into runner
      - name: Checkout code
        #checking out the code
        uses: actions/checkout@v4

      #SET UP PYTHON ENVIRONMENT
        #To install python on runner
      - name: Setup Python
        uses: actions/setup-python@v4
        #To specify the version of python
        with:
          python-version: ${{ env.PYTHON_VERSION}}

      #INSTALL DEPENDENCIES
      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip 
              pip install -r requirements.txt

      #UPLOAD TEST RESULTS
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with: 
          name: pytest-results
          path: htmlcov/
  #RUNNIG TESTS
  test:
    runs-on: ubuntu-latest
    needs: ci-cd
    steps:
      - name: Checkout-code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION}}
      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip 
              pip install -r requirements.txt
      #RUN TESTS
      - name: Run Tests
        run : |
          pip install pytest 
          pytest tests/test_my_func.py

  #CODE COVERAGE REPORT
  Report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout-code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION}}
      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip 
              pip install -r requirements.txt
      - name: Code coverage 
        run: | 
            pip install coverage 
            coverage run -m pytest
            coverage report 
            coverage xml